-- 코드를 입력하세요
# FROM (SELECT B.HISTORY_ID, A.CAR_TYPE, A.DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
#         FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
#         ON A.CAR_ID = B.CAR_ID
#         WHERE CAR_TYPE = '트럭') A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
# ON CAR_TYPE, DURATION IN ()



# SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, B.HISTORY_ID, 
#     CASE 
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN '7일 미만'
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
#         ELSE '90일 이상'
#     END AS PERIOD,
#     C.DISCOUNT_RATE
# FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
# ON A.CAR_ID = B.CAR_ID
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
# ON A.CAR_TYPE = C.CAR_TYPE
# WHERE A.CAR_TYPE = '트럭'


SELECT C.HISTORY_ID, FLOOR(C.DAILY_FEE * (100 - IFNULL(D.DISCOUNT_RATE, 0)) * 0.01 * C.PERIOD) AS FEE
FROM (SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, B.HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN '7일 미만'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
            ELSE '90일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE = '트럭') C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE AND C.DURATION_TYPE = D.DURATION_TYPE
ORDER BY FEE DESC, C.HISTORY_ID DESC