-- 어떤 컬럼이 필요한지 잘 생각해야 한다
-- 1차 조인해서 테이블을 만든 뒤, 그 테이블과 다시 2차 조인(LEFT JOIN)

SELECT C.HISTORY_ID, FLOOR(C.DAILY_FEE * (100 - IFNULL(D.DISCOUNT_RATE, 0)) * 0.01 * C.PERIOD) AS FEE
FROM (SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, B.HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN '7일 미만'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
            ELSE '90일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE = '트럭') C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE AND C.DURATION_TYPE = D.DURATION_TYPE
ORDER BY FEE DESC, C.HISTORY_ID DESC
