-- 코드를 작성해주세요
SELECT B.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A JOIN ITEM_TREE B
ON A.ITEM_ID = B.ITEM_ID
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID
                        FROM ITEM_INFO
                        WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC;






# SELECT IT.ITEM_ID, II.ITEM_NAME, II.RARITY
# FROM ITEM_INFO AS II INNER JOIN ITEM_TREE AS IT
# ON II.ITEM_ID = IT.ITEM_ID
# WHERE IT.PARENT_ITEM_ID IN (SELECT ITEM_ID
#                             FROM ITEM_INFO
#                             WHERE RARITY = "RARE")
# ORDER BY IT.ITEM_ID DESC