-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE (A.FISH_TYPE, A.LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH)
                 FROM FISH_INFO
                 WHERE LENGTH IS NOT NULL
                 GROUP BY FISH_TYPE)
ORDER BY A.ID;

# 처음 작성 코드
# SELECT A.ID, B.FISH_NAME, A.LENGTH
# FROM FISH_INFO A JOIN FISH_NAME_INFO B
# ON A.FISH_TYPE = B.FISH_TYPE
# WHERE LENGTH IN (SELECT MAX(LENGTH)
#                  FROM FISH_INFO
#                  WHERE LENGTH IS NOT NULL
#                  GROUP BY FISH_TYPE)
# ORDER BY A.ID;

# WHERE에서 LENGTH만 확인하면 길이가 60인 다른 물고기가 있을 수도 있다!
# 따라서, FISH_TYPE과 MAX(LENGTH)를 세트로 확인해야 한다!
