-- 코드를 입력하세요
# SELECT B.CATEGORY, SUM(CNT) AS TOTAL_SALES
# FROM (SELECT BOOK_ID, SUM(SALES)
#       FROM BOOK_SALES
#       WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1'
#       GROUP BY BOOK_ID
#      ) A LEFT JOIN BOOK B
#      ON A.BOOK_ID = B.BOOK_ID
# GROUP BY CATEGORY
# ORDER BY CATEGORY

SELECT CATEGORY, SUM(SALES)
FROM BOOK A JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY
ORDER BY CATEGORY